### ISSUE TITLE
Realizar entrega

### ISSUE THREAD

**Issue by svd0009** [svd0009/GESPRO_PracticaGestionTareas_2021#136]

**Comment by svd0009** [comment]
Revisión del material de entrega

**Comment by dab0012** [comment]
Ya esta listo para entregar, cuando le deis el visto bueno lo hacemos.

**Comment by svd0009** [comment]
Generación de los ficheros apropiados #137

**Comment by sdg1002** [comment]
Yo creo que ya estaría para pasarla a revisión
